#To avoid Internet issues, you could install most packages before hand using this
#This isn't comprehensive but if we get comprehensive list from instructors, it will be great. 
#Not sure how will this impact on processing ??
if (! ("reshape" %in% rownames(installed.packages()))) { install.packages("swirl") }
if (! ("reshape2" %in% rownames(installed.packages()))) { install.packages("reshape2") }
if (! ("XLConnect" %in% rownames(installed.packages()))) { install.packages("XLConnect") }
if (! ("xlsx" %in% rownames(installed.packages()))) { install.packages("xlsx") }
if (! ("plyr" %in% rownames(installed.packages()))) { install.packages("plyr") }
if (! ("DMwR" %in% rownames(installed.packages()))) { install.packages("DMwR") }
if (! ("vegan" %in% rownames(installed.packages()))) { install.packages("vegan") }
if (! ("infotheo" %in% rownames(installed.packages()))) { install.packages("infotheo") }
if (! ("dummies" %in% rownames(installed.packages()))) { install.packages("dummies") }
if (! ("ggplot2" %in% rownames(installed.packages()))) { install.packages("ggplot2") }
if (! ("C50" %in% rownames(installed.packages()))) { install.packages("C50") }
if (! ("oblique.tree" %in% rownames(installed.packages()))) { install.packages("oblique.tree") }
if (! ("caret" %in% rownames(installed.packages()))) { install.packages("caret") }
if (! ("doParallel" %in% rownames(installed.packages()))) { install.packages("doParallel") }
if (! ("foreach" %in% rownames(installed.packages()))) { install.packages("foreach") }
if (! ("pROC" %in% rownames(installed.packages()))) { install.packages("pROC") }
if (! ("rpart" %in% rownames(installed.packages()))) { install.packages("rpart") }
if (! ("shiny" %in% rownames(installed.packages()))) { install.packages("shiny") }
if (! ("som" %in% rownames(installed.packages()))) { install.packages("som") }
if (! ("ada" %in% rownames(installed.packages()))) { install.packages("ada") }
if (! ("data.table" %in% rownames(installed.packages()))) { install.packages("data.table") }
if (! ("Deducer" %in% rownames(installed.packages()))) { install.packages("Deducer") }
if (! ("JGR" %in% rownames(installed.packages()))) { install.packages("JGR") }
if (! ("dplyr" %in% rownames(installed.packages()))) { install.packages("dplyr") }
if (! ("plyr" %in% rownames(installed.packages()))) { install.packages("plyr") }
if (! ("e1071" %in% rownames(installed.packages()))) { install.packages("e1071") }
if (! ("forecast" %in% rownames(installed.packages()))) { install.packages("forecast") }
if (! ("GA" %in% rownames(installed.packages()))) { install.packages("GA") }
if (! ("gbm" %in% rownames(installed.packages()))) { install.packages("gbm") }
if (! ("ggplot2" %in% rownames(installed.packages()))) { install.packages("ggplot2") }
if (! ("glmnet" %in% rownames(installed.packages()))) { install.packages("glmnet") }
if (! ("googleVis" %in% rownames(installed.packages()))) { install.packages("googleVis") }
if (! ("igraph" %in% rownames(installed.packages()))) { install.packages("igraph") }
if (! ("lpSolve" %in% rownames(installed.packages()))) { install.packages("lpSolve") }
if (! ("magrittr" %in% rownames(installed.packages()))) { install.packages("magrittr") }
if (! ("mclust" %in% rownames(installed.packages()))) { install.packages("mclust") }
if (! ("NLP" %in% rownames(installed.packages()))) { install.packages("NLP") }
if (! ("openNLP" %in% rownames(installed.packages()))) { install.packages("openNLP") }
if (! ("nnet" %in% rownames(installed.packages()))) { install.packages("nnet") }
if (! ("neuralnet" %in% rownames(installed.packages()))) { install.packages("neuralnet") }
if (! ("qdap" %in% rownames(installed.packages()))) { install.packages("qdap") }
if (! ("quadprog" %in% rownames(installed.packages()))) { install.packages("quadprog") }
if (! ("randomForest" %in% rownames(installed.packages()))) { install.packages("randomForest") }
if (! ("stringr" %in% rownames(installed.packages()))) { install.packages("stringr") }
if (! ("stringi" %in% rownames(installed.packages()))) { install.packages("stringi") }
if (! ("tm" %in% rownames(installed.packages()))) { install.packages("tm") }
if (! ("hts" %in% rownames(installed.packages()))) { install.packages("hts") }
if (! ("TTR" %in% rownames(installed.packages()))) { install.packages("TTR") }
if (! ("TSPred" %in% rownames(installed.packages()))) { install.packages("TSPred") }
if (! ("TSA" %in% rownames(installed.packages()))) { install.packages("TSA") }
if (! ("dlm" %in% rownames(installed.packages()))) { install.packages("dlm") }
if (! ("MASS" %in% rownames(installed.packages()))) { install.packages("MASS") }
if (! ("lubridate" %in% rownames(installed.packages()))) { install.packages("lubridate") }
if (! ("car" %in% rownames(installed.packages()))) { install.packages("car") }
if (! ("dplyr" %in% rownames(installed.packages()))) { install.packages("dplyr") }
if (! ("corrplot" %in% rownames(installed.packages()))) { install.packages("corrplot") }
if (! ("xgboost" %in% rownames(installed.packages()))) { install.packages("xgboost") }
if (! ("RODBC" %in% rownames(installed.packages()))) { install.packages("RODBC") }
if (! ("shiny" %in% rownames(installed.packages()))) { install.packages("shiny") }
if (! ("zoo" %in% rownames(installed.packages()))) { install.packages("zoo") }
if (! ("xts" %in% rownames(installed.packages()))) { install.packages("xts") }
if (! ("ltsa" %in% rownames(installed.packages()))) { install.packages("ltsa") }
if (! ("swirl" %in% rownames(installed.packages()))) { install.packages("swirl") }
if (! ("mlr" %in% rownames(installed.packages()))) { install.packages("mlr") }
if (! ("nloptr" %in% rownames(installed.packages()))) { install.packages("nloptr") }
if (! ("Cubist" %in% rownames(installed.packages()))) { install.packages("Cubist") }
if (! ("Boruta" %in% rownames(installed.packages()))) { install.packages("Boruta") }
if (! ("strucchange" %in% rownames(installed.packages()))) { install.packages("strucchange") }
if (! ("C50" %in% rownames(installed.packages()))) { install.packages("C50") }
if (! ("mice" %in% rownames(installed.packages()))) { install.packages("mice") }
if (! ("h2o" %in% rownames(installed.packages()))) { install.packages("h2o") }
if (! ("rJava" %in% rownames(installed.packages()))) { install.packages("rJava") }
if (! ("data.table" %in% rownames(installed.packages()))) { install.packages("data.table") }
